# Should new players be protected from attacks by other players?
# Default: true
new-player-protection: true

# Should new player protection be removed from a player if they attack someone?
# Default: true
remove-protection-on-attack: true

# How long does protection last on a player (in milliseconds)?
# Default: 30,000 (30 seconds)
protection-time: 30000

# Should new players also be protected from mob attacks?
# Default: true
mob-protection: false

hooks:
  # Hook in to the loot protection expansion and prevent protected players from stealing items. This option is useless if "protect" is set to true in the loot protection config.
  loot-protection: false